# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: tbillah
  imageName: fsl_tbss
  user: tb571
  wd: /home

steps:
- script: |
    docker build -t $(imageName) -f Dockerfile.centos7 --build-arg USER=$(user) --build-arg CWD=$(wd) .
  displayName: 'Build a docker image'
  timeoutInMinutes: 120
    
