# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: pnlbwh_tbss_pipeline
  timeoutInMinutes: 240

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    dockerId: tbillah
    imageName: tbillah/fsl_tbss
    user: pnlbwh
    wd: /home
    testConfigFile: tbss-pipeline-test.yaml


  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: dockerHub


  - task: CopyFiles@2
    displayName: 'Copy test configFile'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/$(testConfigFile)/*.yaml'
      TargetFolder: '$(Agent.BuildDirectory)'

  
  - task: CopyFiles@2
    displayName: 'Copy container structure test'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/container-structure-test-linux-amd64'
      TargetFolder: '$(Agent.BuildDirectory)'

 
  - script: |
        docker pull $(imageName)
        $(Agent.BuildDirectory)/container-structure-test-linux-amd64 test --image $(imageName) --config $(Agent.BuildDirectory)/$(testConfigFile) $(Agent.BuildDirectory)/enigma-test.yaml
    displayName: 'Test the docker image'
    failOnStderr: true


